site_name: OSG Operations
site_url: https://opensciencegrid.github.io/operations/
repo_url: https://github.com/opensciencegrid/operations/
theme: 
  name: readthedocs

pages:
- Home: 'index.md'
- OSG Operations Mission: 'mission.md'
- Services:
  - Installing GlideinWMS Factory: 'services/install-gwms-factory.md'
- Service Level Agreements:
  - 'HTCondor Collector': 'SLA/collector.md'
  - 'MyOSG': 'SLA/myosg.md'
  - 'OASIS': 'SLA/oasis-replica.md'
  - 'OIM': 'SLA/oim.md'
  - 'VOMS': 'SLA/voms.md'
  - 'XDLogin': 'SLA/xdlogin.md'
- External OASIS repositories: 'external-oasis-repos.md'
- Weekly Minutes:
  - '23 April 2018 - Cancelled': 'WeeklyMinutes/23Apr2018.md'
  - '16 April 2018': 'WeeklyMinutes/16Apr2018.md'
  - '9 April 2018': 'WeeklyMinutes/09Apr2018.md'
  - '2 April 2018': 'WeeklyMinutes/02Apr2018.md'
  - '26 March 2018': 'WeeklyMinutes/26Mar2018.md'
  - '12 March 2018': 'WeeklyMinutes/12Mar2018.md'
  - '5 March 2018': 'WeeklyMinutes/05Mar2018.md'
  - '26 February 2018': 'WeeklyMinutes/26Feb2018.md'
  - '19 February 2018': 'WeeklyMinutes/19Feb2018.md'
  - '12 February 2018': 'WeeklyMinutes/12Feb2018.md'
  - '5 February 2018': 'WeeklyMinutes/05Feb2018.md'
  - '29 January 2018': 'WeeklyMinutes/29Jan2018.md'
  - '22 January 2018': 'WeeklyMinutes/22Jan2018.md'
  - '8 January 2018': 'WeeklyMinutes/08Jan2018.md'
  - '18 December 2017': 'WeeklyMinutes/18Dec2017.md'
  - '11 December 2017': 'WeeklyMinutes/11Dec2017.md'
  - '4 December 2017': 'WeeklyMinutes/04Dec2017.md'
  - '27 November 2017': 'WeeklyMinutes/27Nov2017.md'
  - '20 November 2017': 'WeeklyMinutes/20Nov2017.md'
  - '13 November 2017': 'WeeklyMinutes/13Nov2017.md'
  - '6 November 2017': 'WeeklyMinutes/06Nov2017.md'
  - '30 October 2017': 'WeeklyMinutes/30Oct2017.md'
  - '23 October 2017': 'WeeklyMinutes/23Oct2017.md'
  - '16 October 2017': 'WeeklyMinutes/16Oct2017.md'
  - '9 October 2017': 'WeeklyMinutes/09Oct2017.md'
  - '2 October 2017': 'WeeklyMinutes/02Oct2017.md'
  - '25 September 2017': 'WeeklyMinutes/25Sep2017.md'
  - '18 September 2017': 'WeeklyMinutes/18Sep2017.md'
  - '11 September 2017': 'WeeklyMinutes/11Sep2017.md'
  - '28 August 2017': 'WeeklyMinutes/28Aug2017.md'
  - '21 August 2017': 'WeeklyMinutes/21Aug2017.md'
  - '14 August 2017': 'WeeklyMinutes/14Aug2017.md'
  - '07 August 2017': 'WeeklyMinutes/07Aug2017.md'
  - '31 July 2017': 'WeeklyMinutes/31Jul2017.md'
  - '24 July 2017': 'WeeklyMinutes/24Jul2017.md'
  - '17 July 2017': 'WeeklyMinutes/17Jul2017.md'
  - '10 July 2017': 'WeeklyMinutes/10Jul2017.md'
  - '03 July 2017': 'WeeklyMinutes/03Jul2017.md'
  - '26 June 2017': 'WeeklyMinutes/26Jun2017.md'
  - '19 June 2017': 'WeeklyMinutes/19Jun2017.md'
  - '12 June 2017': 'WeeklyMinutes/12Jun2017.md'
  - '05 June 2017': 'WeeklyMinutes/05Jun2017.md'
  - '22 May 2017': 'WeeklyMinutes/22May2017.md'
  - '15 May 2017': 'WeeklyMinutes/15May2017.md'
  - '8 May 2017': 'WeeklyMinutes/08May2017.md'
  - '1 May 2017': 'WeeklyMinutes/01May2017.md'
  - '24 April 2017': 'WeeklyMinutes/24Apr2017.md'
  - '17 April 2017': 'WeeklyMinutes/17Apr2017.md'
  - '10 April 2017': 'WeeklyMinutes/10Apr2017.md'
  - '3 April 2017': 'WeeklyMinutes/03Apr2017.md'
  - '27 March 2017': 'WeeklyMinutes/27Mar2017.md'
  - '20 March 2017': 'WeeklyMinutes/20Mar2017.md'
  - '13 March 2017': 'WeeklyMinutes/13Mar2017.md'
  - '27 February 2017': 'WeeklyMinutes/27Feb2017.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

