
site_name: OSG Documentation
site_url: https://opensciencegrid.github.io/operations
repo_url: https://github.com/opensciencegrid/operations
theme: readthedocs

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- OSG Operations Mission: 'mission.md'

markdown_extensions:
  - admonition
  - osg_markdown.colors

