site_name: OSG Operations
site_url: https://www.opensciencegrid.org/operations/
repo_url: https://github.com/opensciencegrid/operations/
google_analytics: ['UA-69012-29', 'opensciencegrid.github.io']
theme: 
  name: material
  favicon: 'img/favicon.ico'

extra_css:
  - css/extra.css

pages:
- Home: 'index.md'
- OSG Operations Mission: 'mission.md'
- Services:
  - Installing GlideinWMS Factory: 'services/install-gwms-factory.md'
- Service Level Agreements:
  - 'HTCondor Collector': 'SLA/collector.md'
  - 'MyOSG': 'SLA/myosg.md'
  - OASIS (Draft): 'SLA/oasis.md'
  - OASIS Replica: 'SLA/oasis-replica.md'
  - 'OIM': 'SLA/oim.md'
  - 'VOMS': 'SLA/voms.md'
  - 'XDLogin': 'SLA/xdlogin.md'
- External OASIS repositories: 'external-oasis-repos.md'

markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - osg_markdown.colors

